adding QA tests for the new corgi UI
openstax/corgi pull request #523
Opened 2023-01-17 01:47 UTC by omehes

These are the complete QA tests for the new corgi UI
Note, that the `@pytestrail.case("")` does not have a case number as the test cases are not yet updated in testrail. This will happen soon (I almost forgot about it)...

2023-01-17 01:49 UTC, omehes commented
@openstax/ce-tech Integration tests failed due to independecy (playwright) issue... not sure...

2023-01-19 16:01 UTC, therealmarv approved these changes
looks very good for me :+1:

2023-01-20 17:08 UTC, omehes commented
@therealmarv FYI: in case you come back to this PR, I added more commits...

2023-01-23 21:00 UTC, TylerZeroMaster requested changes
Other than these two small problems, this looks and works very well. If you want to resolve the merge conflict, you can just copy the circleci config from corgi-svelte onto this branch so that the contents match on both branches. I can do it if you would like.

2023-01-23 21:28 UTC, omehes commented on backend/app/tests/ui/fixtures/ui.py
> +    base_url = "https://corgi-514.ce.openstax.org/"
Yes, you are right

2023-01-23 21:28 UTC, omehes commented on backend/app/tests/ui/test_create_new_job_button.py
> +    home.fill_version_field(book)
oh, yes. thanks!!!

2023-01-23 22:54 UTC, omehes commented
@TylerZeroMaster I made the changes (no conflict). I assume I can Squash and Merge my branch into corgi_svelte, right?

2023-01-24 15:25 UTC, TylerZeroMaster approved these changes

2023-01-24 19:59 UTC, merged